# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-31 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('pages', models.IntegerField(max_length=20)),
                ('date', models.DateField(max_length=30)),
                ('rating', models.IntegerField(max_length=20)),
                ('comment', models.CharField(max_length=500)),
            ],
        ),
    ]
