# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-31 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
