# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-31 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20180131_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img_url',
            field=models.ImageField(default='static/images/cover.png', upload_to=''),
            preserve_default=False,
        ),
    ]
